% Единый список каналов и карта имя->индекс
% В этом порядке заполняются все таблицы и расчёты
function [names, name2idx] = led_order()
names = { ...
    ra.Channels.WARM2700, ra.Channels.COOL6500, ra.Channels.ROYAL_BLUE, ...
    ra.Channels.BLUE, ra.Channels.CYAN, ra.Channels.PC_CYAN_XEG, ...
    ra.Channels.PC_CYAN_XQE, ra.Channels.LIME, ra.Channels.GREEN, ...
    ra.Channels.PC_AMBER, ra.Channels.RED, ra.Channels.DEEP_RED, ra.Channels.FAR_RED ...
};
name2idx = containers.Map(names, 1:numel(names), 'UniformValues', true);
end

